# Numpy

In [1]:
a = [1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [3]:
import numpy as np
b = np.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


In [4]:
print(type(b))
print(b.ndim) #ndarray的維度
print(b.shape) #ndarray的shape
print(b.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [5]:
print(np.zeros(6)) #產生六個元素均為0的一維array
print(np.zeros((3,6))) #產生18個元素捐維0的二維array
print(np.zeros((2,3,6))) #產生36個元素均為0的三維array

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [6]:
a = np.zeros(16)
print(a)
print(a.shape)
b = a.reshape((4,4)) #改變資料的維度維4x4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


### ndarry 進階操作

In [9]:
my_array = np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5]) #取0, 1, 2, 3, 4位置的值

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [10]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b=np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c=np.array(np.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


### 二維陣列取值

In [1]:
import numpy as np
my_2d_array=np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:]) #第0列的元素
print(my_2d_array[1,]) #第1列的元素
print(my_2d_array[:,0]) #第0欄的元素
print(my_2d_array[1, 1]) #第2列第2欄的元素

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6


In [2]:
import numpy as np
grop = ["蔡G","新人","老鳥"]
pepo = [500, 200, 50]

grop_ar = np.array(grop)
pepo_ar = np.array(pepo)

print(grop)
print(pepo)

['蔡G', '新人', '老鳥']
[500, 200, 50]


In [6]:
#用人數去篩選組別
print(pepo_ar >= 100)
print(grop_ar[pepo_ar>=10])

[ True  True False]
['蔡G' '新人' '老鳥']


In [7]:
#用組別去篩選人數
print(grop_ar != "老鳥")
print(pepo_ar[grop_ar != "老鳥"])

[ True  True False]
[500 200]


### ndarray 空值 nan 無限大 inf

In [9]:
nan_array = np.array([56, 8, 19, 14, 6, np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


### 生成10組標準常態分配(平均為0，標準差為1的常態分配)隨機變數

In [10]:
normal_samples = np.random.normal(size=10)
print(normal_samples)

[-0.43226576  0.55873338 -1.39509241 -1.02470465  0.82171922 -1.35186642
  0.06256788  0.49141982 -0.25672612  0.6070952 ]


### 生成10組介於0~1之間的隨機變數

In [14]:
uniform_samples = np.random.uniform(size=10)
print(uniform_samples)

[0.56751003 0.48318123 0.71931017 0.15279441 0.30392853 0.02860806
 0.60122213 0.03891488 0.17011074 0.57983538]
